version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
      nodejs: 20
  pre_build:
    commands:
      - npm install
      - composer install
  build:
    commands:
      - npm run build
      - ls -l .env*
      - cp .env.$ENVIRONMENT .env
      - php artisan key:generate
      - sed -i "s/DB_PASSWORD=.*/DB_PASSWORD=$DB_PASSWORD/" .env
      - sed -i "s/DB_USERNAME=.*/DB_USERNAME=$DB_USER/" .env
      - sed -i "s/AWS_ACCESS_KEY_ID=.*/AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY/" .env
      - echo $AWS_ACCESS_SECRET
      - sed -i "s#AWS_SECRET_ACCESS_KEY=.*#AWS_SECRET_ACCESS_KEY=$AWS_ACCESS_SECRET#" .env
      - composer install --optimize-autoloader --no-dev
      - cp appspec.$ENVIRONMENT.yml appspec.yml

artifacts:
  files:
    - app/**/*
    - config/*
    - database/**/*
    - routes/*
    - resources/**/*
    - storage/**/*
    - vendor/**/*
    - public/**/*
    - bootstrap/**/*
    - composer.json
    - composer.lock
    - .env
    - deploy/**/*
    - artisan
    - appspec.yml
