name: on-pr-unittest

on:
  pull_request:
    branches:
      - dev

jobs:
  run_unit_test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 33306:3306
        env:
          MYSQL_USER: php_usr
          MYSQL_PASSWORD: php_apsswd
          MYSQL_DATABASE: test_php_app
          MYSQL_ROOT_PASSWORD: password

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4

      # I do not want to modify the .env.testing therefore I spin my own host
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 mariadb" | sudo tee -a /etc/hosts

      # Setup PHP with extensions
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: bcmath, ctype, curl, dom, fileinfo, sodium, filter, hash, mbstring, openssl, pcre, pdo, pdo_mysql, tokenizer, libxml

      # Cache Composer dependencies
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      # Install dependencies
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit tests
        run: |
          sed -i "s/DB_PORT=.*/DB_PORT=33306/" .env.testing &&
          ./vendor/bin/phpunit


