name: "tag-version"

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Git Config
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: Mark date as version
        id: version
        run: echo version=$(date "+%Y%m%d%H%M%S") >> "$GITHUB_OUTPUT"

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
